### PR TITLE
Bitbucket v2: return default value when X-Attempt-Number header is missing

### PR DESCRIPTION
**Pull request by ChrisTitos**
### New Pull Request Checklist

- [x] Run `go fmt` on your files (e.g. `go fmt ./service/common.go`, or on the whole `service` folder: `go fmt ./service/...`)
- [x] Write tests for your code
  - The tests should cover both "success" and "error" cases.
  - The tests should also check **all the returned variables**, don't ignore any returned value!
  - Ideally the tests should be easily readable, we usually use tests to document our code instead of code comments.
    An example, if you'd write a comment like "Given X this function will return Y" or
    "Beware, if the input is X this function will return Y" then you should implement this as
    a unit test, instead of writing it as a comment.
- [x] If your Pull Request is more than a bug fix you should also check `README.md` and change/add the descriptions there - also
  feel free to add yourself as a contributor if you implement support for a new service ;)
- [x] Before creating the Pull Request you should also run `bitrise run test` with the [Bitrise CLI](https://www.bitrise.io/cli),
  to perform all the automatic checks (which will run on your Pull Request when you open it).

### Summary of Pull Request

I read issue #65 which suggests a small fix to support Bitbucket Server (which I need too), I had 15 minutes to spare so I implemented it. Note that I did not do any research into this but I assume @majodev findings are correct.

### CODE REVIEW

**Comment by majodev** [comment]
Hi @ChrisTitos ,

Thanks for the pull. Have not yet had time to write / test the potential bug-fix it on my own locally.
Will test as soon as this gets deployed, hopefully this header is the only thing Atlassian has forgotten to implement in their v2 WebHooks API for BitBucket Server.

Kind regards,
Mario

**Comment by viktorbenei** [comment]
Released in https://github.com/bitrise-io/bitrise-webhooks/releases/tag/1.1.37

Please let us know if this indeed fixes the Bitbucket Server webhook processing issue, and thank you for reporting & for the PR! :)

**Comment by viktorbenei** [comment]
Ohh and of course this is now available in production, on http://hooks.bitrise.io/ :)

**Comment by majodev** [comment]
Just tested, seems like there is still more to do. I'm sorry, did not have time previously to dig deeper on the actual sent payload...

**Request-Headers:**
```
X-Request-Id: 72005ffd-7baa-425f-b432-68f12439810c
Content-Type: application/json; charset=utf-8
X-Event-Key: repo:refs_changed
```


**Request-Body** (personal information stripped):
```json
{
    "eventKey": "repo:refs_changed",
    "date": "2017-11-22T17:44:56+0100",
    "actor": {
        "name": "gitusername",
        "emailAddress": "gitusername@example.com",
        "id": 569,
        "displayName": "Firstname Lastname",
        "active": true,
        "slug": "gitusername",
        "type": "NORMAL"
    },
    "repository": {
        "slug": "project-name",
        "id": 928,
        "name": "project-name",
        "scmId": "git",
        "state": "AVAILABLE",
        "statusMessage": "Available",
        "forkable": true,
        "project": {
            "key": "AW",
            "id": 385,
            "name": "Projectname",
            "public": false,
            "type": "NORMAL"
        },
        "public": false
    },
    "changes": [
        {
            "ref": {
                "id": "refs/heads/master",
                "displayId": "master",
                "type": "BRANCH"
            },
            "refId": "refs/heads/master",
            "fromHash": "5739fca480b83220447a7fb66b9301194ba4a6cb",
            "toHash": "6a460c69f2663c8e0367697c1962469fbe3f71cc",
            "type": "UPDATE"
        }
    ]
}
```

**Response-Headers:**
```
Date: Wed, 22 Nov 2017 16:44:58 GMT
Server: Cowboy
Content-Type: application/json
Connection: keep-alive
Via: 1.1 localhost (Apache-HttpClient/4.4.1 (cache))
Content-Length: 108
```

**Response-Body:**
```json
{"error":"Failed to transform the webhook: Content-Type is not supported: application/json; charset=UTF-8"}

```

**Comment by ChrisTitos** [comment]
Yeah looking at the documentation myself now, Bitbucket Cloud and Server have two very different payload formats:

Cloud:
https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html
Server:
https://confluence.atlassian.com/bitbucketserver/event-payload-938025882.html

Where did you read that Server supports the same API?

**Comment by viktorbenei** [comment]
@majodev can you include a webhook content for a code push? From what you included it seems to be just a new branch create or similar event -> there's no commit message in it for example.

**Comment by ChrisTitos** [comment]
What @majodev posted *is* a code push:

https://confluence.atlassian.com/bitbucketserver055/event-payload-940682389.html

>A user pushes one or more commits to a repository. This payload, with an event key of repo:refs_changed, provides the following fields:

It doesn't seem to include a commit message

**Pull request merged**
