### PR TITLE
Implement Bitbucket Server provider

### PR DESCRIPTION
**Pull request by ChrisTitos**
### New Pull Request Checklist

- [x] Run `go fmt` on your files (e.g. `go fmt ./service/common.go`, or on the whole `service` folder: `go fmt ./service/...`)
- [x] Write tests for your code
  - The tests should cover both "success" and "error" cases.
  - The tests should also check **all the returned variables**, don't ignore any returned value!
  - Ideally the tests should be easily readable, we usually use tests to document our code instead of code comments.
    An example, if you'd write a comment like "Given X this function will return Y" or
    "Beware, if the input is X this function will return Y" then you should implement this as
    a unit test, instead of writing it as a comment.
- [x] If your Pull Request is more than a bug fix you should also check `README.md` and change/add the descriptions there - also
  feel free to add yourself as a contributor if you implement support for a new service ;)
- [x] Before creating the Pull Request you should also run `bitrise run test` with the [Bitrise CLI](https://www.bitrise.io/cli),
  to perform all the automatic checks (which will run on your Pull Request when you open it).

### Summary of Pull Request

To continue with #65 and #66 , I had some time to simply add a dedicated Bitbucket Server provider, as the webhook payloads of Server and Cloud are (still) completely different.
I used the bitbucket-v2 code and tests as a base for this (as I have no prior Go experience).

The events that are supported are:

- `repo:refs_changed` , which include pushes and tag creation
- `pr:opened`, Pull Request opened

### CODE REVIEW

**Comment by viktorbenei** [comment]
Thanks for the PR @ChrisTitos !

Please run the tests locally on your mac, via:

```
bitrise run test
```

Linter issues found:

```
+------------------------------------------------------------------------------+

| (5) Go Lint                                                                  |
+------------------------------------------------------------------------------+
| id: script                                                                   |
| version: 1.1.5                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2017-12-08T20:34:39Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
-> Linting: github.com/bitrise-io/bitrise-webhooks
-> Linting: github.com/bitrise-io/bitrise-webhooks/bitriseapi
-> Linting: github.com/bitrise-io/bitrise-webhooks/config
-> Linting: github.com/bitrise-io/bitrise-webhooks/metrics
-> Linting: github.com/bitrise-io/bitrise-webhooks/service
-> Linting: github.com/bitrise-io/bitrise-webhooks/service/hook
-> Linting: github.com/bitrise-io/bitrise-webhooks/service/hook/assembla
-> Linting: github.com/bitrise-io/bitrise-webhooks/service/hook/bitbucketserver
=> Golint issues found:
/bitrise/go/src/github.com/bitrise-io/bitrise-webhooks/service/hook/bitbucketserver/bitbucketserver.go:23:1: comment on exported type PushEventModel should be of the form "PushEventModel ..." (with optional leading article)
/bitrise/go/src/github.com/bitrise-io/bitrise-webhooks/service/hook/bitbucketserver/bitbucketserver.go:33:6: exported type ChangeItemModel should have comment or be unexported
/bitrise/go/src/github.com/bitrise-io/bitrise-webhooks/service/hook/bitbucketserver/bitbucketserver.go:34:2: struct field RefId should be RefID
/bitrise/go/src/github.com/bitrise-io/bitrise-webhooks/service/hook/bitbucketserver/bitbucketserver.go:41:6: exported type RefModel should have comment or be unexported
/bitrise/go/src/github.com/bitrise-io/bitrise-webhooks/service/hook/bitbucketserver/bitbucketserver.go:42:2: struct field Id should be ID
/bitrise/go/src/github.com/bitrise-io/bitrise-webhooks/service/hook/bitbucketserver/bitbucketserver.go:43:2: struct field DisplayId should be DisplayID
/bitrise/go/src/github.com/bitrise-io/bitrise-webhooks/service/hook/bitbucketserver/bitbucketserver.go:47:6: exported type UserInfoModel should have comment or be unexported
/bitrise/go/src/github.com/bitrise-io/bitrise-webhooks/service/hook/bitbucketserver/bitbucketserver.go:51:6: exported type RepositoryInfoModel should have comment or be unexported
/bitrise/go/src/github.com/bitrise-io/bitrise-webhooks/service/hook/bitbucketserver/bitbucketserver.go:53:2: struct field Id should be ID
/bitrise/go/src/github.com/bitrise-io/bitrise-webhooks/service/hook/bitbucketserver/bitbucketserver.go:60:6: exported type ProjectInfoModel should have comment or be unexported
/bitrise/go/src/github.com/bitrise-io/bitrise-webhooks/service/hook/bitbucketserver/bitbucketserver.go:62:2: struct field Id should be ID
/bitrise/go/src/github.com/bitrise-io/bitrise-webhooks/service/hook/bitbucketserver/bitbucketserver.go:68:6: exported type PullRequestInfoModel should have comment or be unexported
/bitrise/go/src/github.com/bitrise-io/bitrise-webhooks/service/hook/bitbucketserver/bitbucketserver.go:81:6: exported type PullRequestEventModel should have comment or be unexported
/bitrise/go/src/github.com/bitrise-io/bitrise-webhooks/service/hook/bitbucketserver/bitbucketserver.go:88:6: exported type PullRequestRefModel should have comment or be unexported
/bitrise/go/src/github.com/bitrise-io/bitrise-webhooks/service/hook/bitbucketserver/bitbucketserver.go:89:2: struct field Id should be ID
/bitrise/go/src/github.com/bitrise-io/bitrise-webhooks/service/hook/bitbucketserver/bitbucketserver.go:90:2: struct field DisplayId should be DisplayID
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | Go Lint (exit code: 1)                                        | 0.75 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-script/issues             |
| Source: https://github.com/bitrise-io/steps-script                           |
+---+---------------------------------------------------------------+----------+
```

**Comment by ChrisTitos** [comment]
Done :)

**Comment by viktorbenei** [comment]
Thanks for the update & sorry for the delay @ChrisTitos ; I'll try to review this ASAP! :)

**Comment by viktorbenei** [comment]
Huge thanks @ChrisTitos for the PR! :)

Just curious, did you try to run the server locally on your Mac/PC or on your own Heroku? It helps *a lot* with debugging :)

**Comment by viktorbenei** [comment]
I also added you to the "Contributors" section, I hope you don't mind (if you would, just let me know!) ;)

**Comment by viktorbenei** [comment]
Update: release went out, it's in production now on http://hooks.bitrise.io/ ;)

**Comment by ChrisTitos** [comment]
Thanks for merging. It seems to be working in our pipeline :)

I first made the test cases, and then I ran the server locally, and manually made the HTTP request with postman to my local server. The difficulty was more finding out what exactly what the Bitbucket payload was for the different event types

**Comment by viktorbenei** [comment]
Got it, thanks for the infos @ChrisTitos ! :)

There's probably only one this which could be improved, the Pull Request handling / build.

Does PR work too? I think it should if the PR is from the same repository (not from a fork), as at https://github.com/bitrise-io/bitrise-webhooks/pull/67/files#diff-aa6666f77f055f632dd806bda0f58f1dR198 you specify the PR ID and two branches, but not the "Pull Request Repository" (https://github.com/bitrise-io/bitrise-webhooks/blob/ef3f16bd2ac833fc1e0987487874dd2f761932e7/service/hook/bitbucketv2/bitbucketv2.go#L243). This should be enough to do a "pull request build" from a single repo (when both the source & the target are in the same repo, not in a fork) but definitely won't work if the PR is coming from a fork. That said I'm not sure how frequent it is to use forks in a self hosted Bitbucket Server environment.

(Tech note about PR builds: PR builds are meant to test a "pre-merged" code, the state of the code which would be the result if you'd click "merge" on the PR, to provide a more complete test, compared to just simply testing the PRs branch (e.g. feature/a) which might pass tests in itself but might not (in rare cases) after merging it into e.g. "master").

**Comment by viktorbenei** [comment]
In any case huge thanks again @ChrisTitos for your PR & contrib! ;)

**Pull request merged**
