### PR TITLE
Add support for Environment Variables in Slack commands.

### PR DESCRIPTION
**Pull request by nobre84**
Testing new PR with a single commit.

### CODE REVIEW

**Comment by viktorbenei** [comment]
Almost good ;)

```
+------------------------------------------------------------------------------+
| (5) Go Lint                                                                  |
+------------------------------------------------------------------------------+
| id: script                                                                   |
| version: 1.1.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| time: 2016-05-27T15:07:49Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
-> Linting: github.com/bitrise-io/bitrise-webhooks
-> Linting: github.com/bitrise-io/bitrise-webhooks/bitriseapi
=> Golint issues found:
/go/src/github.com/bitrise-io/bitrise-webhooks/bitriseapi/bitriseapi.go:15:6: exported type EnvironmentItem should have comment or be unexported
|                                                                              |
+----+--------------------------------------------------------------+----------+
| 🚫  | Go Lint (exit code: 1)                                       | 0.43 sec |
+----+--------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-script/issues             |
| Source: https://github.com/bitrise-io/steps-script                           |
+----+--------------------------------------------------------------+----------+
```

**Comment by nobre84** [comment]
Now it Lints locally :) Thanks for helping out a go / bitrise noob

**Comment by viktorbenei** [comment]
Now it passes on both PR :D

Can you please close either one and squash the other one?

We'll check the changes ASAP, and hopefully merge quickly after the review - most likely early next week.

**Comment by nobre84** [comment]
Ok! I'm closing this one as it has less context and discussion. Thanks again

**Pull request closed without merging**
