### PR TITLE
Deveo support

### PR DESCRIPTION
**Pull request by kontulai**
This pull request implements support for Deveo - yet another code hosting and collaboration platform.

### New Pull Request Checklist

- [x] Run `go fmt` on your files (e.g. `go fmt ./service/common.go`, or on the whole `service` folder: `go fmt ./service/...`)
- [x] Write tests for your code
  - The tests should cover both "success" and "error" cases.
  - The tests should also check **all the returned variables**, don't ignore any returned value!
  - Ideally the tests should be easily readable, we usually use tests to document our code instead of code comments.
    An example, if you'd write a comment like "Given X this function will return Y" or
    "Beware, if the input is X this function will return Y" then you should implement this as
    a unit test, instead of writing it as a comment.
- [x] If your Pull Request is more than a bug fix you should also check `README.md` and change/add the descriptions there - also
  feel free to add yourself as a contributor if you implement support for a new service ;)
- [ ] Before creating the Pull Request you should also run `bitrise run test` with the [Bitrise CLI](https://www.bitrise.io/cli),
  to perform all the automatic checks (which will run on your Pull Request when you open it).

### Summary of Pull Request

This Pull Request makes the code 10x faster, while reducing
memory consumption by 99%, as well as it implements 5 new service support ...
Something like this ;)

### CODE REVIEW

**Comment by viktorbenei** [comment]
The issue is not in your code - it's a linter error:

```
=> Golint issues found:
/go/src/github.com/bitrise-io/bitrise-webhooks/service/hook/bitbucketv2/bitbucketv2.go:121:22: error strings should not be capitalized or end with punctuation or a newline
```

I'll fix it asap!

**Comment by viktorbenei** [comment]
golint fix PR: https://github.com/bitrise-io/bitrise-webhooks/pull/36

**Comment by kontulai** [comment]
Good to know, I couldn't run `bitrise run test` yet as homebrew doesn't want to co-operate. Let me know if there's anything else I need to do in order to get the PR merged.

**Comment by viktorbenei** [comment]
Everything else seems to be good. Did you test your version somewhere? E.g. on Heroku - https://github.com/bitrise-io/bitrise-webhooks#deploy-to-heroku - it should work fine with a free Heroku account/dyno

**Comment by kontulai** [comment]
@viktorbenei only locally with Requestbin and DHC Rest Client using real payloads from our app. I will give it a spin later today gainst your production environment.

**Comment by viktorbenei** [comment]
All right, thank you for the contribution, I'll try to push this into production ASAP! ;)

**Comment by kontulai** [comment]
Nice! Thank you @viktorbenei!

**Comment by viktorbenei** [comment]
Released in [v1.1.19](https://github.com/bitrise-io/bitrise-webhooks/releases/tag/1.1.19) - now in production! ;)

@kontulai please let us know if there's any issue, once you had the time - we'll try to create a test deveo account too, but might take some time.

**Pull request merged**
